### ISSUE TITLE
动态资源加载 常见问题解答

### ISSUE THREAD

**Issue by qznfbnj** [Kasualix/ModernFix#1]
动态资源加载 常见问题解答 -> 如何开始？

不幸地是，动态资源加载…… → 不幸的是/不幸地，动态资源加载……

末尾新增

使用动态资源功能时最有可能遇到的问题是启动时崩溃或者某些模型的纹理不见了。
**请注意，目前此功能在 Forge 上比在 Fabric 上更稳定、接受了更多测试。**

**Comment by Kasualix** [comment]
done, thx

**Comment by qznfbnj** [comment]
embeddedt把这一行删了
![image](https://github.com/Kasualix/ModernFix/assets/100760086/a115c3c3-9747-4d90-8f2b-17f1c2d097bc)
![image](https://github.com/Kasualix/ModernFix/assets/100760086/e33e7dea-18c0-4940-b297-a543743ebac5)

**Comment by Kasualix** [comment]
好
